from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .io_utils import project_path, read_json, write_json
from .workflow import DrawingReviewWorkflow


DEFAULT_SAMPLE_FILE = r"C:\Users\29580\Desktop\扫描全能王 2026-06-01 15.54(2).pdf"


def main() -> None:
    parser = argparse.ArgumentParser(description="AI spring drawing review MVP")
    subparsers = parser.add_subparsers(dest="command", required=True)

    sample_parser = subparsers.add_parser("sample", help="Run the bundled sample review")
    sample_parser.add_argument("--file", default=DEFAULT_SAMPLE_FILE, help="Optional source drawing path")
    sample_parser.add_argument("--out", default=str(project_path("outputs", "spring_example_review.json")))

    review_parser = subparsers.add_parser("review", help="Run review with recognition candidates")
    review_parser.add_argument("--file", default=None, help="Source drawing path")
    review_parser.add_argument(
        "--candidates",
        required=True,
        nargs="+",
        help="Candidate JSON generated by OCR/Werk24/CAD/vision. Multiple files are merged.",
    )
    review_parser.add_argument("--rules", default=str(project_path("config", "factory_rules.json")))
    review_parser.add_argument("--out", default=str(project_path("outputs", "review.json")))

    ocr_json_parser = subparsers.add_parser("extract-ocr-json", help="Convert OCR text blocks JSON to candidates")
    ocr_json_parser.add_argument("--ocr-json", required=True, help="OCR text blocks JSON")
    ocr_json_parser.add_argument("--out", default=str(project_path("outputs", "ocr_candidates.json")))

    ocr_parser = subparsers.add_parser("extract-ocr", help="Extract OCR candidates with the configured provider")
    ocr_parser.add_argument("--file", required=True, help="Source drawing path")
    ocr_parser.add_argument(
        "--provider",
        choices=["auto", "baidu_ocr", "baidu_paddleocr_vl", "rapidocr"],
        default="auto",
    )
    ocr_parser.add_argument("--out", default=str(project_path("outputs", "ocr_provider_candidates.json")))

    paddleocr_parser = subparsers.add_parser("extract-paddleocr", help="Deprecated alias for extract-ocr --provider auto")
    paddleocr_parser.add_argument("--file", required=True, help="Source drawing path")
    paddleocr_parser.add_argument("--out", default=str(project_path("outputs", "paddleocr_candidates.json")))

    extract_werk24_parser = subparsers.add_parser("extract-werk24", help="Extract candidates with Werk24")
    extract_werk24_parser.add_argument("--file", required=True, help="Source drawing path")
    extract_werk24_parser.add_argument("--out", default=str(project_path("outputs", "werk24_candidates.json")))
    extract_werk24_parser.add_argument(
        "--confirm-upload-to-werk24",
        action="store_true",
        help="Confirm that this drawing may be uploaded to Werk24 for recognition",
    )

    review_werk24_parser = subparsers.add_parser("review-werk24", help="Extract candidates with Werk24 and run review")
    review_werk24_parser.add_argument("--file", required=True, help="Source drawing path")
    review_werk24_parser.add_argument("--rules", default=str(project_path("config", "factory_rules.json")))
    review_werk24_parser.add_argument("--candidates-out", default=str(project_path("outputs", "werk24_candidates.json")))
    review_werk24_parser.add_argument("--out", default=str(project_path("outputs", "werk24_review.json")))
    review_werk24_parser.add_argument(
        "--confirm-upload-to-werk24",
        action="store_true",
        help="Confirm that this drawing may be uploaded to Werk24 for recognition",
    )

    args = parser.parse_args()
    if args.command == "sample":
        candidates_path = project_path("data", "samples", "spring_example_candidates.json")
        rules_path = project_path("config", "factory_rules.json")
        _run_review(args.file, candidates_path, rules_path, args.out)
    elif args.command == "review":
        _run_review(args.file, args.candidates, args.rules, args.out)
    elif args.command == "extract-ocr-json":
        _run_ocr_json_extract(args.ocr_json, args.out)
    elif args.command == "extract-ocr":
        _run_provider_ocr_extract(args.file, args.out, args.provider)
    elif args.command == "extract-paddleocr":
        _run_provider_ocr_extract(args.file, args.out, "auto")
    elif args.command == "extract-werk24":
        _require_werk24_upload_confirmation(args.confirm_upload_to_werk24)
        _run_werk24_extract(args.file, args.out)
    elif args.command == "review-werk24":
        _require_werk24_upload_confirmation(args.confirm_upload_to_werk24)
        _run_werk24_review(args.file, args.rules, args.candidates_out, args.out)


def _run_review(file_path: str | None, candidates_path: str | Path | list[str], rules_path: str | Path, out_path: str | Path) -> None:
    candidates = _read_candidate_files(candidates_path)
    factory_rules = read_json(rules_path)

    workflow = DrawingReviewWorkflow(factory_rules)
    result = workflow.run(file_path, candidates)
    write_json(out_path, result)

    print(f"review written: {out_path}")
    print(f"overall_status: {result['drawing_summary']['overall_status']}")
    print(f"human_review_required: {result['human_review_required']}")
    print(f"erp_ready: {result['erp_ready']}")
    if result["erp_block_reason"]:
        print(f"erp_block_reason: {result['erp_block_reason']}")


def _read_candidate_files(paths: str | Path | list[str]) -> list[dict]:
    if isinstance(paths, (str, Path)):
        paths = [str(paths)]
    candidates: list[dict] = []
    for path in paths:
        payload = read_json(path)
        candidates.extend(payload.get("candidates", payload))
    return candidates


def _run_ocr_json_extract(ocr_json_path: str | Path, out_path: str | Path) -> None:
    from .engines.ocr_adapter import OcrJsonEngine

    candidates = OcrJsonEngine(ocr_json_path).extract()
    payload = {
        "engine": "ocr_json",
        "candidates": candidates,
    }
    write_json(out_path, payload)
    print(f"ocr candidates written: {out_path}")
    print(f"candidate_count: {len(candidates)}")


def _run_provider_ocr_extract(file_path: str | Path, out_path: str | Path, provider: str) -> None:
    from .engines.ocr_providers import UnifiedOcrEngine

    payload = UnifiedOcrEngine(provider=provider).extract_with_raw(file_path)
    write_json(out_path, payload)
    print(f"ocr candidates written: {out_path}")
    print(f"provider: {payload.get('provider')}")
    print(f"text_block_count: {len(payload.get('texts', []))}")
    print(f"candidate_count: {len(payload.get('candidates', []))}")


def _run_werk24_extract(file_path: str | Path, out_path: str | Path) -> None:
    payload = _extract_werk24_or_exit(file_path)
    write_json(out_path, payload)
    print(f"werk24 candidates written: {out_path}")
    print(f"candidate_count: {len(payload['candidates'])}")
    print(f"raw_message_count: {len(payload['raw_messages'])}")


def _run_werk24_review(
    file_path: str | Path,
    rules_path: str | Path,
    candidates_out_path: str | Path,
    review_out_path: str | Path,
) -> None:
    payload = _extract_werk24_or_exit(file_path)
    write_json(candidates_out_path, payload)

    factory_rules = read_json(rules_path)
    workflow = DrawingReviewWorkflow(factory_rules)
    result = workflow.run(str(file_path), payload["candidates"])
    write_json(review_out_path, result)

    print(f"werk24 candidates written: {candidates_out_path}")
    print(f"review written: {review_out_path}")
    print(f"candidate_count: {len(payload['candidates'])}")
    print(f"overall_status: {result['drawing_summary']['overall_status']}")
    print(f"human_review_required: {result['human_review_required']}")
    print(f"erp_ready: {result['erp_ready']}")
    if result["erp_block_reason"]:
        print(f"erp_block_reason: {result['erp_block_reason']}")


def _extract_werk24_or_exit(file_path: str | Path) -> dict:
    from .engines.werk24_adapter import Werk24Engine

    try:
        return Werk24Engine().extract_with_raw(file_path)
    except RuntimeError as exc:
        print(f"werk24 error: {exc}", file=sys.stderr)
        raise SystemExit(2) from exc


def _require_werk24_upload_confirmation(confirmed: bool) -> None:
    if confirmed:
        return
    print(
        "werk24 upload confirmation required: this command sends the drawing file "
        "to Werk24's external API. Re-run with --confirm-upload-to-werk24 only after "
        "you are allowed to upload this drawing.",
        file=sys.stderr,
    )
    raise SystemExit(3)


if __name__ == "__main__":
    main()
