import assert from "node:assert/strict";
import fs from "node:fs";

const appSource = fs.readFileSync(new URL("../frontend/app.js", import.meta.url), "utf8");
const cssSource = fs.readFileSync(new URL("../frontend/styles.css", import.meta.url), "utf8");

assert.match(appSource, /generation-readiness/);
assert.match(appSource, /generation-jobs/);
assert.match(appSource, /window\.setInterval\(\(\) => \{ void poll\(\); \}, 2000\)/);
assert.match(appSource, /data-action="compare-generation"/);
assert.match(appSource, /data-action="retry-generation-preview"/);
assert.match(appSource, /data-action="preview-generation-pdf"/);
assert.doesNotMatch(appSource, /data-action="preview-generation-pdf"[^`]*<a class="button-link"/);
assert.match(appSource, /data-action="recreate-generation"/);
assert.match(appSource, /function openGenerationPdf/);
assert.match(appSource, /previewUrl\.searchParams\.set\("inline", "1"\)/);
assert.match(appSource, /<iframe src="\$\{escapeHtml\(previewUrl\.toString\(\)\)\}"/);
assert.match(appSource, /download="\$\{escapeHtml\(artifact\.filename \|\| "drawing\.pdf"\)\}">下载 PDF<\/a>/);
assert.match(appSource, /function generationJobNeedsTracking/);
assert.match(appSource, /Date\.now\(\) - started < 30000/);
assert.match(appSource, /\/preview\/retry/);
assert.match(appSource, /PDF 已生成，对比预览生成失败/);
assert.match(appSource, /TaskId/);
assert.match(appSource, /generating_3d_error: "三维模型生成失败"/);
assert.match(appSource, /generating_2d_error: "二维图生成失败"/);
assert.match(appSource, /const showProgress = !terminal \|\| job\.status === "failed"/);
assert.match(appSource, /role="progressbar"/);
assert.match(appSource, /statusMessage && job\.status !== "failed"/);
assert.match(appSource, /data-action="approve-generation"/);
assert.match(appSource, /job\.status === "completed" && !job\.is_final \? `<button type="button" class="primary-action" data-action="approve-generation"/);
assert.doesNotMatch(appSource, /job\.status === "completed" && !job\.is_stale && !job\.is_final/);
assert.match(appSource, /当前正在编辑的参数不会自动恢复/);
assert.match(appSource, /if \(action === "approve"\) \{[\s\S]*?state\.generationJobs = state\.generationJobs\.map/);
assert.match(appSource, /return item\.is_final \? \{ \.\.\.item, is_final: false/);
assert.match(appSource, /data-compare-mode="side-by-side"/);
assert.match(appSource, /data-compare-mode="original"/);
assert.match(appSource, /data-compare-mode="generated"/);
assert.match(appSource, /data-role="generation-zoom-out"/);
assert.match(appSource, /data-role="generation-zoom-in"/);
assert.match(appSource, /data-role="generation-reset-view"/);
assert.match(appSource, /data-role="generation-active-pane"/);
assert.match(appSource, /data-role="generation-link-views"/);
assert.match(appSource, /const paneViews = \{/);
assert.match(appSource, /syncLinkedView\(pane\.key\)/);
assert.match(appSource, /data-role="generation-compare-viewport"/);
assert.match(appSource, /addEventListener\("wheel"/);
assert.match(appSource, /addEventListener\("pointerdown"/);
assert.match(appSource, /addEventListener\("pointermove"/);
assert.match(appSource, /new ResizeObserver\(scheduleRender\)/);
assert.match(appSource, /const minZoom = 0\.25/);
assert.match(appSource, /const maxZoom = 5/);
assert.doesNotMatch(appSource, /data-compare-mode="overlay"/);
assert.doesNotMatch(appSource, /generation-opacity/);
assert.match(appSource, /历史审图修订/);
assert.match(appSource, /待真实 SolidWorks \/ ERP 接入/);
assert.match(appSource, /标准化为可选功能/);
assert.doesNotMatch(appSource, /等待生成标准化方案/);
assert.doesNotMatch(appSource, /parent_generation_id/);
assert.match(cssSource, /\.generation-compare-viewport/);
assert.match(cssSource, /\.generation-compare-viewport\.dragging/);
assert.match(cssSource, /\.generation-preview-thumbnail/);
assert.match(cssSource, /\.generation-preview-status\.failed/);
assert.match(cssSource, /\.generation-pdf-dialog/);
assert.match(cssSource, /\.generation-progress\.failed/);
assert.match(cssSource, /background: #dc2626/);
assert.doesNotMatch(cssSource, /\.generation-compare-canvas\.overlay/);
assert.doesNotMatch(cssSource, /--generation-opacity/);

console.log("generation closed-loop UI test passed");
